Updated Container (OS, Java) Management Scripts

diff --git a/containers/java/utils/common-functions b/containers/java/utils/common-functions
--- a/containers/java/utils/common-functions
+++ b/containers/java/utils/common-functions
@@ -8,12 +8,67 @@
 # Common Functions used in other Scripts
 #---------------------------------------------------------------
 
+# Get the name of the script (without the path)
+script_name=$(basename "$0")
+
 # Function to set VERSION from input or default to 21
 set_version() {
   if [[ -n "$1" ]]; then
     VERSION="$1"
   else
     VERSION=21
+  fi
+}
+
+# Show Help
+show_help() {
+  echo "----------------------------------------------------------------"
+  echo "Java Container Management. "
+  echo "Copyright (c) Araf Karsh Hamid, 2025"
+
+  # Check if the script name is "abc"
+  if [ "$script_name" = "build" ]; then
+    echo "Use buildx to create Multi-Architecture (arm64/amd64) Images"
+  fi
+  echo "----------------------------------------------------------------"
+  echo "INVALID INPUTS! Missing OS Name and/or Java Version Number"
+  echo "----------------------------------------------------------------"
+  if [ "$script_name" = "build" ]; then
+    echo "Usage: $0 [alpine, ubuntu, ubuntu-openjdk] [23, 21, 17, 11]"
+  fi
+    if [ "$script_name" = "buildx" ]; then
+    echo "Usage: $0 [alpine, ubuntu-openjdk] [21, 17, 11]"
+  fi
+  echo "Examples"
+  echo "----------------------------------------------------------------"
+  echo "$0 alpine 21"
+  echo "$0 alpine 17"
+  if [ "$script_name" = "build" ]; then
+    echo "$0 ubuntu 21"
+    echo "$0 ubuntu 23"
+  fi
+  echo "$0 ubuntu-openjdk 17"
+  echo "$0 ubuntu-openjdk 21"
+  echo "----------------------------------------------------------------"
+
+}
+
+# Validate the Paramters to the Shell Script
+validate_params() {
+    local expected_count=2  # Expected number of parameters
+    local actual_count=$#   # Number of parameters passed
+
+    if [ "$actual_count" -ne "$expected_count" ]; then
+        show_help
+        exit 1
+    fi
+}
+
+# Check if the OS is supported for Multi-Architecture
+validate_buildx_os() {
+  if [ "$script_name" = "buildx" ]; then
+    echo "$1 Not Supported!. Try using alpine or ubuntu-openjdk"
+    exit 1
   fi
 }
 
@@ -25,10 +80,12 @@ determine_config() {
       DOCKER_FILE="Dockerfiles/Dockerfile.alpine.$VERSION"
       ;;
     ubuntu)
+      validate_buildx_os
       SERVICE="java:$VERSION"
       DOCKER_FILE="Dockerfiles/Dockerfile.ubuntu.$VERSION"
       ;;
     ubuntu-x86)
+      validate_buildx_os
       SERVICE="java:$VERSION-x86"
       DOCKER_FILE="Dockerfiles/Dockerfile.ubuntu.x86.$VERSION"
       ;;
@@ -39,21 +96,7 @@ determine_config() {
     *)
       SERVICE="java:$VERSION-alpine"
       DOCKER_FILE="Dockerfiles/Dockerfile.alpine.$VERSION"
-      echo "----------------------------------------------------------------"
-      echo "Java Container Management. "
-      echo "Copyright (c) Araf Karsh Hamid, 2025"
-      echo "NO INPUTS! Defaulting to $ORG/$SERVICE"
-      echo "----------------------------------------------------------------"
-      echo "Options: $0 [alpine, ubuntu, ubuntu-openjdk] [23, 21, 17, 11]"
-      echo "Examples"
-      echo "----------------------------------------------------------------"
-      echo "$0 alpine 21 [supports arm64 & amd64]"
-      echo "$0 alpine 17 [supports arm64 & amd64]"
-      echo "$0 ubuntu 21 [supports arm64 only]"
-      echo "$0 ubuntu 23 [supports arm64 only]"
-      echo "$0 ubuntu-openjdk 17 [supports arm64 & amd64]"
-      echo "$0 ubuntu-openjdk 21 [supports arm64 & amd64]"
-      echo "----------------------------------------------------------------"
+      show_help
       ;;
   esac
 }
